# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.2.0
_src_path: git@github.com:MeteoSwiss-APN/mch-python-blueprint.git
email: simon.adamov@meteoswiss.ch
full_name: Simon Adamov
github_username: sadamov
module_name: realtime_pollen_calibration
project_github: MeteoSwiss-APN/realtime-pollen-calibration
project_name: Realtime Pollen Calibration
project_short_description: Simon Adamov's Realtime Pollen Calibration
project_slug: realtime-pollen-calibration
python_version: '3.10'
version: 0.1.0
year: '2022'

